#!/usr/bin/env bash
# Deploy Ajo Circle + a TEST "USDC" token to Stellar TESTNET.
#
# Creates throwaway identities in the stellar CLI config (~/.config/stellar),
# funds them with Friendbot, issues a classic test asset USDC:<issuer>,
# wraps it in a Stellar Asset Contract (SAC), and deploys the ajo contract.
# Secrets never leave the stellar CLI keystore; only public IDs are written to
# deployments/testnet.env.
#
# NOTE: "USDC" here is a TEST TOKEN issued by a throwaway account — it is NOT
# Circle's USDC and has no value.
set -euo pipefail
cd "$(dirname "$0")/.."

NET=testnet
P=${AJO_PREFIX:-ajo}
ADMIN=$P-admin
ISSUER=$P-issuer
CODE=USDC
OUT=deployments/testnet.env
LOG=deployments/testnet-deploy.log
: > "$LOG"

ensure_key() {
  if stellar keys address "$1" >/dev/null 2>&1; then
    echo "identity $1 exists: $(stellar keys address "$1")"
  else
    stellar keys generate "$1" --network $NET --fund
    echo "identity $1 created + funded: $(stellar keys address "$1")"
  fi
}

# run a CLI command, tee stderr (where tx hashes are logged) into the log
run() { "$@" 2> >(tee -a "$LOG" >&2); }

ensure_key "$ADMIN"
ensure_key "$ISSUER"
ISSUER_G=$(stellar keys address "$ISSUER")
ASSET="$CODE:$ISSUER_G"

echo "== build contract"
stellar contract build --package ajo
WASM=target/wasm32v1-none/release/ajo.wasm

echo "== deploy SAC for test asset $ASSET"
TOKEN_ID=$(stellar contract id asset --asset "$ASSET" --network $NET)
if ! run stellar contract asset deploy --asset "$ASSET" --source-account "$ISSUER" --network $NET --alias "$P-usdc" >/dev/null; then
  echo "(asset deploy failed - assuming the SAC already exists)"
  stellar contract alias add "$P-usdc" --id "$TOKEN_ID" --network $NET --overwrite >/dev/null 2>&1 || true
fi
echo "token SAC: $TOKEN_ID"

echo "== deploy ajo contract"
CONTRACT_ID=$(run stellar contract deploy --wasm "$WASM" --source-account "$ADMIN" --network $NET --alias "$P-circle")
echo "ajo contract: $CONTRACT_ID"

cat > "$OUT" <<ENV
# Public testnet deployment info (no secrets). Generated by scripts/deploy-testnet.sh
NETWORK=testnet
RPC_URL=https://soroban-testnet.stellar.org
NETWORK_PASSPHRASE="Test SDF Network ; September 2015"
AJO_CONTRACT_ID=$CONTRACT_ID
TOKEN_CONTRACT_ID=$TOKEN_ID
TOKEN_CODE=$CODE
TOKEN_ISSUER=$ISSUER_G
ADMIN_ADDRESS=$(stellar keys address "$ADMIN")
ENV
echo "wrote $OUT"
cat "$OUT"
