# Deploy Ajo Circle + a TEST "USDC" token to Stellar TESTNET (Windows PowerShell).
# Mirrors scripts/deploy-testnet.sh. Secrets stay in the stellar CLI keystore;
# only public IDs are written to deployments/testnet.env.
# NOTE: "USDC" here is a TEST TOKEN issued by a throwaway account, not Circle USDC.
param([string]$Prefix = "ajo", [string]$ExpectedToken = "CATRFP36R3S26TGC2W5VQKV7ZFWKQ2B2HAJI6RXUTSB442UBTPJDO5MB")
$v1Id = "CBH6266NK6UGOLQ6NEUWM7EYANTMHOB5CLCJ27LZ3ARAARP52CIST4EZ"
$ErrorActionPreference = "Stop"
Set-Location (Join-Path $PSScriptRoot "..")
$net = "testnet"
$admin = "$Prefix-admin"
$issuer = "$Prefix-issuer"

function Ensure-Key($name) {
  stellar keys address $name 2>$null | Out-Null
  if ($LASTEXITCODE -ne 0) {
    stellar keys generate $name --network $net --fund
    if ($LASTEXITCODE -ne 0) { throw "could not create identity $name" }
    Write-Host "identity $name created + funded"
  } else { Write-Host "identity $name exists" }
}

Ensure-Key $admin
Ensure-Key $issuer
$issuerG = (stellar keys address $issuer).Trim()
$adminG = (stellar keys address $admin).Trim()
$asset = "USDC:$issuerG"

Write-Host "== build contract"
stellar contract build --package ajo
if ($LASTEXITCODE -ne 0) { throw "build failed" }
$wasm = "target/wasm32v1-none/release/ajo.wasm"

Write-Host "== deploy SAC for test asset $asset"
$tokenId = (stellar contract id asset --asset $asset --network $net).Trim()
stellar contract asset deploy --asset $asset --source-account $issuer --network $net --alias "$Prefix-usdc" | Out-Null
if ($LASTEXITCODE -ne 0) { Write-Host "(asset deploy failed - assuming the SAC already exists)" }
Write-Host "token SAC: $tokenId"
if ($tokenId -ne $ExpectedToken) { throw "refusing to deploy: token SAC $tokenId != expected $ExpectedToken" }

(Get-FileHash -Algorithm SHA256 $wasm).Hash.ToLower() | Write-Host

Write-Host "== deploy ajo v2 contract (constructor pins the token)"
$contractId = (stellar contract deploy --wasm $wasm --source-account $admin --network $net --alias "$Prefix-circle-v2" -- --token $tokenId).Trim()
if ($LASTEXITCODE -ne 0) { throw "deploy failed" }
Write-Host "ajo contract (v2): $contractId"

# Keep the previous (v1, no collateral) ID visible as deprecated - never drop it.
$prevLine = ""
if (Test-Path "deployments/testnet.env") {
  $prev = (Select-String -Path "deployments/testnet.env" -Pattern '^AJO_CONTRACT_ID=(.*)$' | Select-Object -First 1)
  if ($prev) {
    $prevId = $prev.Matches[0].Groups[1].Value.Trim()
    if ($prevId -and $prevId -ne $v1Id -and $prevId -ne $contractId) { $prevLine = "AJO_CONTRACT_ID_PREVIOUS=$prevId" }
  }
}

@"
# Public testnet deployment info (no secrets). Generated by scripts/deploy-testnet.ps1
NETWORK=testnet
RPC_URL=https://soroban-testnet.stellar.org
NETWORK_PASSPHRASE="Test SDF Network ; September 2015"
AJO_CONTRACT_ID=$contractId
# v1: no collateral, do not use (see README)
AJO_CONTRACT_ID_V1_DEPRECATED=$v1Id
$prevLine
TOKEN_CONTRACT_ID=$tokenId
TOKEN_CODE=USDC
TOKEN_ISSUER=$issuerG
ADMIN_ADDRESS=$adminG
"@ | Set-Content -Encoding ascii "deployments/testnet.env"
Get-Content "deployments/testnet.env"
Write-Host "Copy these into web/.env.local (see web/.env.example)."
