# Deploy Ajo Circle + a TEST "USDC" token to Stellar TESTNET (Windows PowerShell).
# Mirrors scripts/deploy-testnet.sh. Secrets stay in the stellar CLI keystore;
# only public IDs are written to deployments/testnet.env.
# NOTE: "USDC" here is a TEST TOKEN issued by a throwaway account, not Circle USDC.
param([string]$Prefix = "ajo")
$ErrorActionPreference = "Stop"
Set-Location (Join-Path $PSScriptRoot "..")
$net = "testnet"
$admin = "$Prefix-admin"
$issuer = "$Prefix-issuer"

function Ensure-Key($name) {
  stellar keys address $name 2>$null | Out-Null
  if ($LASTEXITCODE -ne 0) {
    stellar keys generate $name --network $net --fund
    if ($LASTEXITCODE -ne 0) { throw "could not create identity $name" }
    Write-Host "identity $name created + funded"
  } else { Write-Host "identity $name exists" }
}

Ensure-Key $admin
Ensure-Key $issuer
$issuerG = (stellar keys address $issuer).Trim()
$adminG = (stellar keys address $admin).Trim()
$asset = "USDC:$issuerG"

Write-Host "== build contract"
stellar contract build --package ajo
if ($LASTEXITCODE -ne 0) { throw "build failed" }
$wasm = "target/wasm32v1-none/release/ajo.wasm"

Write-Host "== deploy SAC for test asset $asset"
$tokenId = (stellar contract id asset --asset $asset --network $net).Trim()
stellar contract asset deploy --asset $asset --source-account $issuer --network $net --alias "$Prefix-usdc" | Out-Null
if ($LASTEXITCODE -ne 0) { Write-Host "(asset deploy failed - assuming the SAC already exists)" }
Write-Host "token SAC: $tokenId"

Write-Host "== deploy ajo contract"
$contractId = (stellar contract deploy --wasm $wasm --source-account $admin --network $net --alias "$Prefix-circle").Trim()
if ($LASTEXITCODE -ne 0) { throw "deploy failed" }
Write-Host "ajo contract: $contractId"

@"
# Public testnet deployment info (no secrets). Generated by scripts/deploy-testnet.ps1
NETWORK=testnet
RPC_URL=https://soroban-testnet.stellar.org
NETWORK_PASSPHRASE="Test SDF Network ; September 2015"
AJO_CONTRACT_ID=$contractId
TOKEN_CONTRACT_ID=$tokenId
TOKEN_CODE=USDC
TOKEN_ISSUER=$issuerG
ADMIN_ADDRESS=$adminG
"@ | Set-Content -Encoding ascii "deployments/testnet.env"
Get-Content "deployments/testnet.env"
Write-Host "Copy these into web/.env.local (see web/.env.example)."
