#!/usr/bin/env bash
# End-to-end Ajo Circle run on Stellar TESTNET with 3 throwaway members.
#   round 0: all three contribute -> payout to member 1 (before deadline)
#   round 1: only members 1 & 2 contribute -> wait for deadline -> payout to
#            member 2, member 3 recorded as defaulted
# Writes deployments/testnet-e2e.md with explorer links. No secrets are printed.
set -euo pipefail
cd "$(dirname "$0")/.."
source deployments/testnet.env
NET=testnet
P=${AJO_PREFIX:-ajo}
ASSET="$TOKEN_CODE:$TOKEN_ISSUER"
CONTRIB=100000000      # 10 USDC (7 decimals)
PERIOD=${PERIOD:-90}   # seconds per round (short, for the demo)
REPORT=deployments/testnet-e2e.md
TMP=$(mktemp)
LINKS=$(mktemp)
step() { # step "<label>" cmd...  -> runs cmd, records explorer link from stderr
  local label=$1; shift
  local out
  out=$("$@" 2>"$TMP") || { cat "$TMP" >&2; exit 1; }
  local tx
  tx=$(grep -oE 'stellar.expert/explorer/testnet/tx/[0-9a-f]{64}' "$TMP" | tail -1 || true)
  if [[ -n "$tx" ]]; then echo "| $label | [${tx##*/}](https://$tx) |" >> "$LINKS"; fi
  echo "  $label ${tx:+-> https://$tx}" >&2
  printf '%s' "$out"
}

for i in 1 2 3; do
  id=$P-m$i
  if ! stellar keys address $id >/dev/null 2>&1; then
    stellar keys generate $id --network $NET --fund >/dev/null 2>&1
    echo "created + funded $id" >&2
    step "trustline $id" stellar tx new change-trust --source-account $id --line "$ASSET" --network $NET >/dev/null
    step "mint 100 test USDC to $id" stellar tx new payment --source-account $P-issuer \
      --destination "$(stellar keys address $id)" --asset "$ASSET" --amount 1000000000 --network $NET >/dev/null
  fi
done
M1=$(stellar keys address $P-m1); M2=$(stellar keys address $P-m2); M3=$(stellar keys address $P-m3)

inv() { stellar contract invoke --id "$AJO_CONTRACT_ID" --network $NET "$@"; }
bal() { stellar contract invoke --id "$TOKEN_CONTRACT_ID" --network $NET --source-account $P-admin -- balance --id "$1" 2>/dev/null | tr -d '"'; }

echo "== create circle (3 members, 10 USDC, ${PERIOD}s rounds)" >&2
CID=$(step "create_circle" inv --source-account $P-admin -- create_circle \
  --admin "$ADMIN_ADDRESS" --token "$TOKEN_CONTRACT_ID" --contribution $CONTRIB \
  --members "[\"$M1\",\"$M2\",\"$M3\"]" --period_secs $PERIOD)
echo "circle id: $CID" >&2

echo "== round 0: everyone pays" >&2
for i in 1 2 3; do
  step "round 0 contribute m$i" inv --source-account $P-m$i -- contribute --circle_id $CID --member "$(stellar keys address $P-m$i)" >/dev/null
done
B1=$(bal "$M1")
step "round 0 payout -> m1" inv --source-account $P-admin -- payout --circle_id $CID >/dev/null
A1=$(bal "$M1")
echo "  m1 balance $B1 -> $A1" >&2
R0=$(inv --source-account $P-admin --send=no -- get_round_status --circle_id $CID --round 0 2>/dev/null)

echo "== round 1: m3 skips" >&2
step "round 1 contribute m1" inv --source-account $P-m1 -- contribute --circle_id $CID --member "$M1" >/dev/null
step "round 1 contribute m2" inv --source-account $P-m2 -- contribute --circle_id $CID --member "$M2" >/dev/null
if inv --source-account $P-admin -- payout --circle_id $CID >/dev/null 2>&1; then
  echo "unexpected: early payout succeeded" >&2; exit 1
else
  echo "  early payout correctly rejected (PayoutNotReady)" >&2
fi
echo "  waiting $((PERIOD + 15))s for the round deadline..." >&2
sleep $((PERIOD + 15))
step "round 1 payout -> m2 (m3 defaulted)" inv --source-account $P-admin -- payout --circle_id $CID >/dev/null
R1=$(inv --source-account $P-admin --send=no -- get_round_status --circle_id $CID --round 1 2>/dev/null)
REC3=$(inv --source-account $P-admin --send=no -- get_member_record --circle_id $CID --member "$M3" 2>/dev/null)
CIRCLE=$(inv --source-account $P-admin --send=no -- get_circle --circle_id $CID 2>/dev/null)

{
  echo "# Testnet end-to-end run"
  echo
  echo "Generated by \`scripts/e2e-testnet.sh\` on $(date -u +'%Y-%m-%d %H:%M UTC')."
  echo
  echo "- Ajo contract: [\`$AJO_CONTRACT_ID\`](https://stellar.expert/explorer/testnet/contract/$AJO_CONTRACT_ID)"
  echo "- Test token SAC (USDC test asset, NOT real USDC): [\`$TOKEN_CONTRACT_ID\`](https://stellar.expert/explorer/testnet/contract/$TOKEN_CONTRACT_ID)"
  echo "- Circle id: \`$CID\` · contribution 10 USDC · ${PERIOD}s rounds"
  echo "- Members: m1 \`$M1\`, m2 \`$M2\`, m3 \`$M3\`"
  echo
  echo "| Step | Transaction |"
  echo "|---|---|"
  cat "$LINKS"
  echo
  echo "## Results"
  echo
  echo "Round 0 (all paid) — m1 balance \`$B1\` → \`$A1\` (+30 USDC)."
  echo
  echo '```json'
  echo "$R0"
  echo '```'
  echo
  echo "Round 1 (m3 defaulted, paid out after the deadline):"
  echo
  echo '```json'
  echo "$R1"
  echo '```'
  echo
  echo "m3 member record:"
  echo
  echo '```json'
  echo "$REC3"
  echo '```'
  echo
  echo "Circle state after the run:"
  echo
  echo '```json'
  echo "$CIRCLE"
  echo '```'
} > "$REPORT"
rm -f "$TMP" "$LINKS"
echo "wrote $REPORT" >&2
